---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ignored-but-required
spec:
  interval: 5m
  timeout: 10m # The default is normally 5m
  install:
    timeout: 10m # The default is normally 5m
  upgrade:
    timeout: 10m # The default is normally 5m
