apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helmreleases/account-processor.yaml
- helmreleases/api-account.yaml
- namespace.yaml
patches:
- path: flux-timeouts.yaml
  target:
    kind: HelmRelease
