apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: api-account
  namespace: backend
spec:
  values:
    application:
      env:
        ENV: sandbox
      image:
        tag: v0.1.71
      replicaCount: 3
