apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: account-processor
  namespace: backend
spec:
  chart:
    spec:
      chart: backend
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: org-incubator
        namespace: flux-repos
      version: 1.0.50
  releaseName: account-processor
  values:
    application:
      env:
        CLUSTER: ${cluster_name}
        ACCOUNT_API_PRIVATE_URL: http://api-account-private.backend.svc.cluster.local
        AUTHORIZATION_API_PRIVATE_URL: http://api-authorization-private.backend.svc.cluster.local
        KAFKA_TOPIC_ACCOUNT_EVENTS: account-events
        KRATOS_ADMIN_API_URL: http://kratos-admin.ory.svc.cluster.local
      image:
        repository: us.gcr.io/org-private/account-processor
        tag: v0.0.0
      replicaCount: 1
      resources:
